import { type Metadata } from "next";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import { PostHogProvider } from "./providers";
import { IdentifyUser } from "@/components/IdentifyUser";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SyncClerkToDB } from "@/components/SyncClerkToDB";
import { ThemeProvider } from "@/components/ThemeProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Selve – Discover. Understand. Grow.",
  description: "Generated by create next app",
  manifest: "/manifest.json",
  icons: {
    icon: [
      { rel: "icon", url: "favicons/icon.ico" },
      // the contrast of these is too dark that's why it's commented out
      // { rel: "icon", type: "image/png", sizes: "16x16", url: "favicons/favicon-16x16.png" },
      // { rel: "icon", type: "image/png", sizes: "32x32", url: "favicons/favicon-32x32.png" },
      { rel: "apple-touch-icon", url: "favicons/apple-touch-icon.png" },
      { rel: "icon", type: "image/png", sizes: "192x192", url: "favicons/android-chrome-192x192.png" },
      { rel: "icon", type: "image/png", sizes: "512x512", url: "favicons/android-chrome-512x512.png" },
    ]
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <PostHogProvider>
      <ClerkProvider>
        <html lang="en" suppressHydrationWarning>
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
            <ThemeProvider>
              <header className="flex justify-end items-center p-4 gap-4 h-16">
                <SignedOut>
                  <SignInButton />
                  <SignUpButton />
                </SignedOut>
                <SignedIn>
                  <UserButton />
                  <IdentifyUser />
                  <SyncClerkToDB />
                </SignedIn>
              </header>
              {children}
            </ThemeProvider>
          </body>
        </html>
      </ClerkProvider>
    </PostHogProvider>
  );
}
