// src/app/layout.tsx
import { type Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { PostHogProvider } from "./providers";
import {
  Geist,
  Geist_Mono,
  Inter,
  Poppins,
  Crimson_Text,
} from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/ThemeProvider";
import { Header } from "@/components/header/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

const crimsonText = Crimson_Text({
  variable: "--font-crimson-text",
  subsets: ["latin"],
  weight: ["400", "600"],
});

export const metadata: Metadata = {
  title: "Selve – Discover. Understand. Grow.",
  description: "Generated by create next app",
  manifest: "/manifest.json",
  icons: {
    icon: [
      { rel: "icon", url: "favicons/icon.ico" },
      // the contrast of these is too dark that's why it's commented out
      // { rel: "icon", type: "image/png", sizes: "16x16", url: "favicons/favicon-16x16.png" },
      // { rel: "icon", type: "image/png", sizes: "32x32", url: "favicons/favicon-32x32.png" },
      { rel: "apple-touch-icon", url: "favicons/apple-touch-icon.png" },
      {
        rel: "icon",
        type: "image/png",
        sizes: "192x192",
        url: "favicons/android-chrome-192x192.png",
      },
      {
        rel: "icon",
        type: "image/png",
        sizes: "512x512",
        url: "favicons/android-chrome-512x512.png",
      },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <PostHogProvider>
      <ClerkProvider>
        <html lang="en" suppressHydrationWarning>
          <body
            className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} ${poppins.variable} ${crimsonText.variable} antialiased`}
          >
            <ThemeProvider>
              <Header />
              {children}
            </ThemeProvider>
          </body>
        </html>
      </ClerkProvider>
    </PostHogProvider>
  );
}
